# eventsource.yaml
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: detection-car
  namespace: user1
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    example:
      endpoint: /event
      method: POST
      port: "12000"
--- 
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: detection-speed 
  namespace: user1
spec:
  service:
    ports:
      - port: 12001
        targetPort: 12001
  webhook:
    example:
      endpoint: /event
      method: POST
      port: "12001"
--- 
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: detection-pedestrian
  namespace: user1
spec:
  service:
    ports:
      - port: 12002
        targetPort: 12002
  webhook:
    example:
      endpoint: /event
      method: POST
      port: "12002"