apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: vehicle-detected
  namespace: user1
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    vehicle-detected:
      port: "12000"
      endpoint: /vehicle-detected
      method: POST
---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: over-speed
  namespace: user1
spec:
  service:
    ports:
      - port: 12001
        targetPort: 12001
  webhook:
    over-speed:
      port: "12001"
      endpoint: /over-speed
      method: POST
---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: pedestrian-detected
  namespace: user1
spec:
  service:
    ports:
      - port: 12002
        targetPort: 12002
  webhook:
    pedestrian-detected:
      port: "12002"
      endpoint: /pedestrian-detected
      method: POST
